/**
 * Generates `src/css/variables.css` from the TypeScript token constants.
 * Run via `pnpm --filter @sutra/tokens gen:css`. The CSS file is the runtime,
 * framework-agnostic theming surface; the TS constants are the source of truth.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { darkVars, rootVars } from "../internal/css-model";

const HEADER = `/*
 * AUTO-GENERATED by @sutra/tokens.
 * Do not edit by hand — run \`pnpm --filter @sutra/tokens gen:css\` instead.
 * Source of truth: packages/tokens/src/*.ts
 */`;

function renderBlock(selector: string, vars: Record<string, string>, lead: string[]): string {
  const decls = [...lead, ...Object.entries(vars).map(([name, value]) => `${name}: ${value};`)]
    .map((line) => `  ${line}`)
    .join("\n");
  return `${selector} {\n${decls}\n}`;
}

/**
 * Motion primitives that ship with the token CSS so framework-agnostic
 * consumers (and the `@sutra/ui` Skeleton `animation="shimmer"`) get the
 * keyframe without any build step. Respects reduced-motion preferences.
 */
const MOTION = `@keyframes sutra-shimmer {
  0% { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}

.sutra-shimmer {
  background: linear-gradient(
    90deg,
    var(--sutra-color-surface-muted) 0%,
    var(--sutra-color-surface-subtle) 50%,
    var(--sutra-color-surface-muted) 100%
  );
  background-size: 200% 100%;
  animation: sutra-shimmer 1.6s ease-in-out infinite;
}

@media (prefers-reduced-motion: reduce) {
  .sutra-shimmer {
    animation: none;
  }
}`;

function renderCss(): string {
  return [
    HEADER,
    "",
    renderBlock(":root", rootVars, ["color-scheme: light;"]),
    "",
    renderBlock(".dark", darkVars, ["color-scheme: dark;"]),
    "",
    MOTION,
    "",
  ].join("\n");
}

const outFile = fileURLToPath(new URL("../css/variables.css", import.meta.url));
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, renderCss(), "utf8");

console.log(
  `Wrote ${Object.keys(rootVars).length} root vars + ${Object.keys(darkVars).length} dark overrides to ${outFile}`,
);
